### ISSUE TITLE
训练时长

### ISSUE THREAD

**Issue by boxbox2** [wangpeng000/VisualInspection#2]
这代码训练需要多长时间？我看了代码好像主要时间都在
![image](https://github.com/wangpeng000/VisualInspection/assets/56194614/a0c21d75-c763-488b-9ca0-1b46c4dfeff7)
这个上面，请问这个需要花费多长时间？

**Comment by wangpeng000** [comment]
你好，这个项目是几年前做的了，只是前段时间整理了一下。当时我记得是训练要几个小时，8小时以内好像。当时的gpu是1080 Ti，现在应该会快很多。你图片上的地方是挺耗时间的，但是具体细节我已经忘记了，不好意思。

**Comment by boxbox2** [comment]
> 你好，这个项目是几年前做的了，只是前段时间整理了一下。当时我记得是训练要几个小时，8小时以内好像。当时的gpu是1080 Ti，现在应该会快很多。你图片上的地方是挺耗时间的，但是具体细节我已经忘记了，不好意思。

谢谢您的回复，如果我想基于您的这篇工作进行改进的话，您有什么建议嘛？您在做异常检测这块的工作嘛？期待您的回复

**Comment by wangpeng000** [comment]
@boxbox2 抱歉回复地比较晚，如果你想在我的这篇自监督的文章上进行改进的话，我觉得(我现在不做这块的工作了，不一定可靠)可以从一下方面改进，1：提出更高效的自监督方式(个人认为有点难度)；2：借助这两年来的大模型来提供先验辅助最终的异常检测。我之前看到过ICLR 2024好像有类似的文章，你可以看一下。以上仅是我的个人建议，太久没关注这个方向了，不知道是否会有用，欢迎随时提问。

**Comment by xin94wang** [comment]
@wangpeng000 @boxbox2 大佬们好，请问代码中需要的ngtpy这个包是怎么安装的啊？我通过pip install ngtpy安装，提示找不到这个库

(zuidi) D:\1-study\2-code\VisualInspection-main>pip install ngtpy
ERROR: Could not find a version that satisfies the requirement ngtpy (from versions: none)
ERROR: No matching distribution found for ngtpy

(zuidi) D:\1-study\2-code\VisualInspection-main>pip3 install ngt
ERROR: Could not find a version that satisfies the requirement ngt (from versions: none)
ERROR: No matching distribution found for ngt

**Comment by xin94wang** [comment]
> 你好，这个项目是几年前做的了，只是前段时间整理了一下。当时我记得是训练要几个小时，8小时以内好像。当时的gpu是1080 Ti，现在应该会快很多。你图片上的地方是挺耗时间的，但是具体细节我已经忘记了，不好意思。

您好，请问您说的这个8小时左右是指的mvtec数据集的其中一个类别还是15个类别一起啊？

**Comment by wangpeng000** [comment]
@xin94wang 一个类别，每个类别都要单独train。 ngt那个库好像维护不太好，我是20-21年做的这些实验，当时可以装上，现在情况不太清楚了

**Comment by wangpeng000** [comment]
@boxbox2 https://github.com/caoyunkang/AdaCLIP ，这篇文章是今年的ECCV，就是借助CLIP来完成异常检测的，供参考。

**Comment by boxbox2** [comment]
> @boxbox2 https://github.com/caoyunkang/AdaCLIP ，这篇文章是今年的ECCV，就是借助CLIP来完成异常检测的，供参考。

哇谢谢大佬的持续关注，我现在在做OOD方向的异常检测，我会认真阅读这篇论文寻找思路的。再次感谢您的回复
